### ISSUE TITLE
pvalue available?

### ISSUE THREAD

**Issue by Ivy-ops** [lakerwsl/RDB#1]
Hi developer, 
Thanks for creating this package. Can this package generate raw p-value? 
Thanks.

**Comment by lakerwsl** [comment]
Hi Ivy-ops,

This method is an iterative method, i.e. report a few significant ones in each iteration. The p-value for each component can be different at each iteration. In the next update, I will try to report the p-values in all iterations. 

Best,
Shulei

**Comment by Ivy-ops** [comment]
Thanks! @lakerwsl
