### ISSUE TITLE
Error Message "could not find function BFGSAlgorithm"

### ISSUE THREAD

**Issue by mkbwang** [lakerwsl/RDB#2]
Hello, when I try to include extra covariates there is an error message saying "could not find function BFGSAlgorithm". A minimal reproducible example is

```
m=50
d=100 
P=matrix(runif(m*d),nrow=m,ncol=d)
Z=rep(0,m)
Z[1:(m/2)]=1
X <- data.frame(X=rnorm(m))
result <- rdb(P=P,Z=Z, X=X, fdr=T) # error message here
```

Is there any dependent R packages that I need to install? Thank you!

**Comment by BoYuan07** [comment]
Hi, thanks for letting us know. We just fixed the problem and you could try to remove the package (remove.packages('RDB')) and reinstall it. The dependency packages(ATE) should be automatically installed, and please let us know if there is any question.

**Comment by mkbwang** [comment]
Thanks for your followup. Unfortunately there is another error message. It's called `Error in t(bdiag(C1, C2)) : object 'Csparse_transpose' not found`. Can you identify the issue? Thanks!

**Comment by BoYuan07** [comment]
Hi, could you try to update package Matrix (uninstall and reinstall it, reopen R)? If it doesn't work, you can email me your R code.

Best,
Bo
